try :
    print(x)
except NameError as e:
    print(e)